I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 7, in script
    image bg kitchen = im.Fit(
  File "game/script.rpy", line 7, in <module>
    image bg kitchen = im.Fit(
AttributeError: module 'renpy.display.im' has no attribute 'Fit'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 7, in script
    image bg kitchen = im.Fit(
  File "C:\Users\user\Documents\RenPy\renpy-8.3.7-sdk\renpy\ast.py", line 933, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\user\Documents\RenPy\renpy-8.3.7-sdk\renpy\python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 7, in <module>
    image bg kitchen = im.Fit(
AttributeError: module 'renpy.display.im' has no attribute 'Fit'

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.7.25031702
Autobiography 1.0
Thu May  8 17:24:45 2025
